<div class="cool-style-album col-xs-6 col-sm-6 col-lg-4" id="album_<?php echo $wo['album']['id'];?>">
	<div class="album_parent">
		<div class="avatar">
			<a href="<?php echo $wo['album']['url'];?>" data-ajax="?link1=post&id=<?php echo $wo['album']['id'];?>">
				<?php if ($wo['album']['blur'] == 1) { ?>
					<audio src="<?php echo $wo['album']['first_image'];?>" alt="<?php echo $wo['album']['first_image']; ?> Music" class="image_blur"></audio>
		      	<?php }else{ ?>
		      		<audio src="<?php echo $wo['album']['first_image'];?>" alt="<?php echo $wo['album']['first_image']; ?> Music" ></audio>
		      	<?php } ?>
			</a>
			<span class="alb_count" title="<?php echo $wo['lang']['songs']; ?>"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentcolor" d="M4,6H2V20A2,2 0 0,0 4,22H18V20H4M18,7H15V12.5A2.5,2.5 0 0,1 12.5,15A2.5,2.5 0 0,1 10,12.5A2.5,2.5 0 0,1 12.5,10C13.07,10 13.58,10.19 14,10.5V5H18M20,2H8A2,2 0 0,0 6,4V16A2,2 0 0,0 8,18H20A2,2 0 0,0 22,16V4A2,2 0 0,0 20,2Z"></path></svg> <?php echo Wo_CountAlbumImages($wo['album']['id']);?></span>
			<div class="album-name">
				<h4><?php echo $wo['album']['album_name']; ?></h4>
			</div>
		</div>
	</div>
</div>
<style>#album_<?php echo $wo['album']['id'];?> .album_parent .avatar:before, #album_<?php echo $wo['album']['id'];?> .album_parent .avatar:after {background-image: url('<?php echo $wo['album']['first_image'];?>')}</style>